accounts/urls.py
"""Define URL patterns for accounts."""

from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    # Login a user
    path('', include('django.contrib.auth.urls')),
    # Register a user
    path('register/', views.register, name='register'),
    # User settings
    path('settings/', views.settings, name='settings'),
    # Check email
    path('check_email/', views.check_email, name='check_email'),
    # Check user
    path('check_user/', views.check_user, name='check_user'),
]

app/urls.py
"""Definre URL patterns."""

from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    # Home page.
    path('', views.index, name='index'),
    # Blog posts.
    path('posts/', views.posts, name='posts'),
    # Details for a single post.
    path('posts/<int:post_id>', views.post, name='post'),
    # Handle forms for comments.
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),
    # TOS
    path('tos/', views.tos, name='tos'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('app.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

app/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    """A blog post."""

    title = models.CharField(max_length=150)
    text = RichTextField()
    image = models.ImageField(upload_to='images/', blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    locked = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'posts'

    def __str__(self):
        """Return a string reprsentation of the model."""
        return f"{self.title}"
    
class Comment(models.Model):
    """A comment by a client."""
    
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)
    text = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'comments'

    def __str__(self):
        return f"{self.text}"

accounts/forms.py
from typing import Any
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):

    email = forms.EmailField(max_length=254, help_text="Email")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

app/forms.py
from django import forms

from .models import Comment

class CommentForm(forms.ModelForm):
    """A form for a comment."""

    class Meta:
        model = Comment
        fields = ['text']

accounts/views.py
import json

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .forms import CustomUserCreationForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from django.http import JsonResponse

def register(request):
    """Register a new user."""

    if request.method != 'POST':
        form = CustomUserCreationForm()
    else:
        # Process completed form.
        form = CustomUserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log user in and redirect
            login(request, new_user)
            return redirect('app:posts')
        for field, errors in form.errors.items():
            for error in errors:
                messages.error(request, f"{field}: {error}")

    context = {'form': form}
    return render(request, 'registration/register.html', context)

@require_POST
def check_email(request):

    data = json.loads(request.body.decode('utf-8'))
    email = data.get('email')

    if email is not None:
        exists = User.objects.filter(email=email).exists()
        if exists:
            return JsonResponse({"message": "taken"}, status=200)
        else:
            return JsonResponse({"message": "available"}, status=200)
    else:
        return JsonResponse({"message": "bad request"}, status=400)

@require_POST
def check_user(request):

    data = json.loads(request.body.decode('utf-8'))
    username = data.get('user')

    if username is not None:
        exists = User.objects.filter(username=username).exists()
        if exists:
            return JsonResponse({"message": "taken"}, status=200)
        else:
            return JsonResponse({"message": "available"}, status=200)
    else:
        return JsonResponse({"message": "bad request"}, status=400)
        

def settings(request):
    """Show settings of a user."""

    return render(request, 'registration/settings.html', {})

app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse

from .models import Post, Comment
from .forms import CommentForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 

def index(request):
    """Render the home page."""

    return render(request, 'index.html', {})

def posts(request):
    """Render a list of posts."""

    posts = Post.objects.order_by('-date_added')
    paginator = Paginator(posts, 4)
    page_num = request.GET.get('page')

    try:
        page_obj = paginator.page(page_num)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {'page_obj': page_obj}

    return render(request, 'posts.html', context)

def post(request, post_id):
    """Render a single post."""

    post = Post.objects.get(id=post_id)
    comments = Comment.objects.filter(post=post).order_by('-date_added')
    context = {'post': post,
               'comments': comments}
    
    return render(request, 'post.html', context)

def new_comment(request, post_id):
    """Handle a form to create a user comment."""

    post = get_object_or_404(Post, id=post_id)

    if request.method == 'POST':
        # POST data submitted; process it!
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = post
            new_comment.save()

            # success
            return JsonResponse({"success": True}, status=201)
        else:
            return JsonResponse({"success": False}, status=401)
    
    return render('app:post', post_id=post_id)

def tos(request):

    return render(request)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Personal Portfolio</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% include 'navbar.html' %}
    <main>
        {% block content %}{% endblock content %}
    </main>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/comments.html
{% load static %}
<div class="comment-section">
    <div class="comments-header">
        <p>Comments</p>
    </div>
    <hr class="post-separator">
    <div class="comment-form-container">
        {% if post.locked %}
            <p>Comments locked for this post.</p>
        {% else %}
            {% if user.is_authenticated %}
                <form id="comment-form">
                    {% csrf_token %}
            
                    <input type="text" name="text" id="comment-text" placeholder="add comment" maxlength="150" required>
                    <input type="submit" value="Post" id="post-button">
                </form>
            {% else %}
                <p>Login to post comments</p>
            {% endif %}
        {% endif %}
    </div>
    <div class="comments-container">
        {% for comment in comments %}
        <div class="comment">
            <div class="comment-heading">
                <p id="user-comment-date"> {{ comment.date_added|date:'n/j/y' }}</p>
            </div>
            <p id="user-comment">{{ comment.text }}</p>
        </div>
        {% endfor %}
    </div>
</div>
<script>
    const csrf = "{{ csrf_token }}";
</script>
<script src="{% static 'js/comment.js' %}"></script>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="portfolio">
    <div class="profile">
        <img src="{% static 'images/default.jpg' %}" alt="default placeholder">
    </div>
    <div class="links">
        <a href="#" id="github"><img src="{% static 'images/github.svg' %}" alt="github icon"></a>
        <a href="#" id="linkedin"><img src="{% static 'images/linkedin.svg' %}" alt="linkedin icon"></a>
        <a href="#" id="form"><img src="{% static 'images/rectangle-list-solid.svg' %}" alt="list icon"></a>
    </div>
    <div class="about-me">
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit. Provident corrupti ab quis vero quaerat
            iure soluta vitae, fugit vel, maiores doloribus inventore atque, perferendis obcaecati? Eos illum
            exercitationem obcaecati ipsum!
        </p>
    </div>
</div>
{% endblock content %}

templates/navbar.html
{% load static %}
<div class="user-bar">
    <div class="user-links">
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Log Out</a>
            <a href="{% url 'accounts:settings' %}" id="gear"><img src="{% static 'images/gear-solid.svg' %}" alt=""></a>
        {% else %}
            <a href="{% url 'accounts:login' %}">Log In</a>
        {% endif %}
    </div>
</div>
<div class="nav-bar">
    <div class="nav-links">
        <a href="{% url 'app:index' %}">Home</a>
        <a href="{% url 'app:posts' %}">Posts</a>
        <div id="toggle">
            <label class="switch">
                <input type="checkbox" id="toggleSwitch" checked>
                <span class="slider"></span>
            </label>
        </div>
    </div>
</div>

templates/pagination.html
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
    {% endif %}
    {% if page_obj.number >= 4 %}
            <a href="?page=1">1</a>
        {% if page_obj.number >= 5 %}
            <a href="?page={{ page_obj.number|add:'-3' }}">&hellip;</a>
        {% endif %}
    {% endif %}
    {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
            <a href="?page={{ num }}" class="active">{{ num }}</a>
        {% elif num >= page_obj.number|add:'-2' and num < page_obj.number|add:'3' %}
            <a href="?page={{ num }}">{{ num }}</a>
        {% endif %}
    {% endfor %}
    {% if page_obj.number < page_obj.paginator.num_pages|add:'-3' %}
        <a href="?page={{ page_obj.number|add:'5' }}">&hellip;</a>
        <a href="?page={{ page_obj.paginator.count }}">{{ page_obj.paginator.count }}</a>
    {% elif page_obj.number < page_obj.paginator.num_pages|add:'-2' %}
        <a href="?page={{ page_obj.paginator.count }}">{{ page_obj.paginator.count }}</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
    {% endif %}
</div>

templates/post.html
{% extends 'base.html' %}
{% block content %}
<div class="post">
    {% if post.image %}
    <div class="post-image">
        <img src="{{ post.image.url }}" alt="{{ post.title }}">
    </div>
    {% endif %}
    <div class="post-header">
        <p class="title">{{ post.title }}</p>
        <p class="post-date">{{ post.date_added|date:'M d, Y' }}</p>
    </div>
    <div class="post-content">
        {% if post.text %}
            <p class="post-text">{{ post.text|safe }}</p>
        {% else %}
            <p>No text</p>
        {% endif %}
    </div>
</div>
{% include 'comments.html'%}
{% endblock content %}

templates/posts.html
{% extends 'base.html' %}
{% block content %}
<div class="posts-container">
    <div class="cards">
        {% for post in page_obj %}
        <a href="{% url 'app:post' post.id %}">
        <div class="card">
            <div class="card-image">
                <img src="{{ post.image.url }}" alt="{{ post.title }}">
            </div>
            <div class="card-contents">
                <h2 class="card-title">{{ post.title }}</h2>
                <p class="card-date">{{ post.date_added|date:'M d, Y' }}</p>
                <p class="card-desc">{{ post.text|safe|truncatechars:200 }}</p>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
    <div class="pagination-container">
        {% include 'pagination.html' %}
    </div>
</div>
{% endblock content %}